name: reddit-rag
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - faiss-cpu
  - pip
  - pip:
    - streamlit==1.35.0
    - langchain==0.2.11
    - langchain-community==0.2.10
    - openai>=1.35.0
    - sentence-transformers==3.0.1
    - torch>=2.0.0
    - numpy>=1.21.0,<2.0
    - tiktoken==0.7.0
    - tqdm==4.66.4
    - psutil==5.9.8
