# Streamlit 설정 - M2 MacBook Air 최적화

[server]
# 메모리 효율성을 위한 설정
maxUploadSize = 50
enableXsrfProtection = true
enableCORS = false

[browser]
# 자동 브라우저 열기
gatherUsageStats = false
serverAddress = "localhost"

[theme]
# 다크 테마 (눈 피로 감소)
base = "dark"
primaryColor = "#7B68EE"  # 보라색 (꿈 테마)
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[runner]
# 메모리 최적화
fastReruns = true
magicEnabled = false

[client]
# 캐싱 설정
caching = true
showErrorDetails = true 